"""Live trading scope policy for polybot2."""

LIVE_TRADING_VERSION = "v1"

DEFAULT_PROVIDER = None

LIVE_BETTING_LEAGUES = {
    "mlb",
    "fifwc",
    "epl",
    "ucl",
    "laliga",
    "rgm",
    "rgw",
    "birmm",
    "birmw",
    "tyler",
    "centurion",
    "perugia",
    "heilbronn",
    "prostejov",
    "foggia",
    "makarska",
    "queen",
    "stuttgart",
    "libema_m",
    "libema_w",
    "modena",
    "bratislava",
    "ilkley_w",
    "cattolica",
    "ilkley_m",
    "lyon",
    "tucuman",
    "halle_m",
    "queen_m",
    "berlin_w",
    "nott_w",
    "nott_m",
    "cs2",
    "lol",
    "dota2",
    "fifa_friendly",
}
LIVE_BETTING_MARKET_TYPES = {
    "mlb": ["nrfi",
            "totals",
            "moneyline",
            "spreads",
            "baseball_team_first_five_winner",
            "baseball_team_first_five_total",
            "baseball_team_first_five_spread",
            "baseball_game_extra_innings",
            ],
    "epl":["moneyline",
           "totals",
           "both_teams_to_score",
           "spreads",
           "soccer_halftime_result",
           "total_corners"],
    "ucl": ["moneyline",
            "totals",
            "both_teams_to_score",
            "spreads",
            "soccer_halftime_result",
            "total_corners",],
    "fifwc": ["moneyline",
            "totals",
            "both_teams_to_score",
            "spreads",
            "soccer_halftime_result",
            "total_corners",],
    "laliga": ["moneyline",
            "totals",
            "both_teams_to_score",
            "spreads",
            "soccer_halftime_result",],
    "tennis": ["moneyline",
               "tennis_first_set_winner",
               "tennis_set_totals",
               "tennis_set_handicap",
               "tennis_match_totals",
               "tennis_first_set_totals",],
    "cs2": ["moneyline",
            "child_moneyline",
            "totals",
            "map_handicap",],
    "lol": ["moneyline",
            "child_moneyline",
            "totals",
            "map_handicap",],
    "dota2": ["moneyline",
              "child_moneyline",
              "totals",
              "map_handicap",],
    "fifa_friendly": ["moneyline",
                      "totals",
                      "both_teams_to_score",
                      "spreads",
                      "soccer_halftime_result",
                      "total_corners",],
}

# Centralized hotpath execution profile used by league runtime plugins.
# Leagues without their own entry fall back to their sport_family key
# (e.g., all tennis leagues use the "tennis" entry unless overridden).
HOTPATH_EXECUTION_POLICY = {
    "mlb": {
        "size_shares": 1000.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
        "secondary_amount_usdc": 1000.0,
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.99,
        "market_overrides": {
        "moneyline": {"size_shares": 2500.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 2500.0, "secondary_limit_price": 0.99,},
        # TOTALS SAFETY
        "totals:over":  {"size_shares": 500.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 2500.0, "secondary_limit_price": 0.99,}, 
        "totals:under": {"size_shares": 2000.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 1000.0, "secondary_limit_price": 0.99,}, 
        # NRFI 
        "nrfi:no":   {"size_shares": 2000.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 1000.0, "secondary_limit_price": 0.99,},
        # SAFE F5 MARKETS
        "baseball_team_first_five_winner": {"size_shares": 100.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 100.0, "secondary_limit_price": 0.99,},
        "baseball_team_first_five_spread": {"size_shares": 100.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 100.0, "secondary_limit_price": 0.99,},
        "baseball_game_extra_innings":{"size_shares": 100.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 100.0, "secondary_limit_price": 0.99,},
        # F5 TOTALS SIMILAR TO REGULAR TOTALS
        "baseball_team_first_five_total:over": {"size_shares": 5.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 5.0, "secondary_limit_price": 0.99,},
        "baseball_team_first_five_total:under": {"size_shares": 100.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 100.0, "secondary_limit_price": 0.99,},
        },
    },
    "fifwc": {
        "size_shares": 50.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.90,
        "secondary_amount_usdc": 50.0,
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.95,
        "market_overrides": {
	    "total_corners": {"size_shares": 500.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 500.0, "secondary_limit_price": 0.99,},
        "soccer_halftime_result": {"amount_usdc": 250.0, "size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 500.0, "secondary_limit_price": 0.99,},
        "moneyline":{"size_shares": 500.0,  "limit_price": 0.99,
                    "secondary_amount_usdc": 500.0, "secondary_limit_price": 0.99,},
        "spread":{"size_shares": 500.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 500.0, "secondary_limit_price": 0.99,},
                    },

    },
    "epl": {
        "size_shares": 25.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.90,
        "secondary_amount_usdc": 25.0,
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.95,
        "market_overrides": {
	    "total_corners": {"size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_limit_price": 0.99,},
        "soccer_halftime_result": {"size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_size_shares": 250.0, "secondary_limit_price": 0.99,},
        "moneyline":{"size_shares": 250.0,  "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_limit_price": 0.99,},
        "spread":{"size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_limit_price": 0.99,},
                    },

    },
    "ucl": {
        "size_shares": 50.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.90,
        "secondary_amount_usdc": 50.0,
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.95,
        "market_overrides": {
	    "total_corners": {"size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_size_shares": 250.0, "secondary_limit_price": 0.99,},
        "soccer_halftime_result": {"amount_usdc": 250.0, "size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_limit_price": 0.99,},
        "moneyline":{"size_shares": 250.0,  "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_limit_price": 0.99,},
        "spread":{"size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_limit_price": 0.99,},
                    },
    },
    "laliga": {
        "size_shares": 50.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.9,
        "secondary_amount_usdc": 25.0,
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.9,
        "market_overrides": {
	    "total_corners": {"size_shares": 150.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_size_shares": 150.0, "secondary_limit_price": 0.99,},
        "soccer_halftime_result": {"amount_usdc": 150.0, "size_shares": 150.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_limit_price": 0.99,},
        "moneyline":{"size_shares": 150.0,  "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_limit_price": 0.99,},
        "spread":{"size_shares": 150.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_limit_price": 0.99,},
                    },
    },
    "tennis": {
        "size_shares": 2250.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
        "secondary_amount_usdc": 2250.0,
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.99,
        "retirement": {
            "size_shares": 100.0,
            "time_in_force": "GTC",
            "limit_price": 0.49,
            "secondary_amount_usdc": 100.0,
            "secondary_time_in_force": "FAK",
            "secondary_limit_price": 0.49,
        },
    },
    "cs2":{
        "size_shares": 5.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
        "secondary_amount_usdc": 5.0,
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.99,
    },
    "lol":{
        "size_shares": 5.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
    },
    "dota2":{
        "size_shares": 5.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
    },
    "fifa_friendly": {
        "size_shares": 5.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
    },
}

# Runtime timing controls for live snapshot refresh and subscription windows.
# Leagues without their own entry fall back to their sport_family key.
HOTPATH_RUNTIME_POLICY = {
    "mlb": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 5,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 1800,
        "ws_core_idx": 5,
        "submitter_core_idx": 6,
    },
    "epl": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 1,
        "submitter_core_idx": 2,
    },
    "ucl": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 3,
        "submitter_core_idx": 4,
    },
    "laliga": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 7,
        "submitter_core_idx": 8,
    },
    "tennis": {
        "plan_horizon_hours": 24,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 1800,
        # "game_refresh_interval_seconds": 3600,
        "ws_core_idx": 3,
        "submitter_core_idx": 4,
    },
    "cs2": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 43200,
        "refresh_interval_seconds": 1800,
        "game_refresh_interval_seconds": 300,
        "ws_core_idx": 1,
        "submitter_core_idx": 2,
    },
    "lol": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 43200,
        "refresh_interval_seconds": 1800,
        "ws_core_idx": 0,
        "submitter_core_idx": 7,
    },
    "dota2": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 43200,
        "refresh_interval_seconds": 1800,
        "ws_core_idx": 0,
        "submitter_core_idx": 7,
    },
    "fifa_friendly": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 3,
        "submitter_core_idx": 4,
    },
    "fifwc": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 1,
        "submitter_core_idx": 2,
    },
}
