"""Live trading scope policy for polybot2."""

LIVE_TRADING_VERSION = "v1"

DEFAULT_PROVIDER = None

LIVE_BETTING_LEAGUES = {
    "mlb",
    "epl",
    "ucl",
    "laliga",
    "rolgar",
    "garros",
}
LIVE_BETTING_MARKET_TYPES = {
    "mlb": ["nrfi", 
            "totals", 
            "moneyline",
            "spreads"],
    "epl":["moneyline", 
           "totals", 
           "both_teams_to_score", 
           "spreads", 
           "soccer_halftime_result", 
           "total_corners"],
    "ucl": ["moneyline", 
            "totals", 
            "both_teams_to_score", 
            "spreads", 
            "soccer_halftime_result",],
    "laliga": ["moneyline",
            "totals",
            "both_teams_to_score",
            "spreads",
            "soccer_halftime_result",],
    "rolgar": ["moneyline",
            "tennis_first_set_winner",
            "tennis_set_totals",
            "tennis_set_handicap",],
    "garros":["moneyline",
            "tennis_first_set_winner",
            "tennis_set_totals",
            "tennis_set_handicap",],
}

# Centralized hotpath execution profile used by league runtime plugins.
HOTPATH_EXECUTION_POLICY = {
    "mlb": {
        "amount_usdc": 150.0,
        "size_shares": 150.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
        "secondary_amount_usdc": 150.0,
        "secondary_size_shares": 150.0, 
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.99,
    },
    "epl": {
        "amount_usdc": 25.0,
        "size_shares": 25.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.90,
        "secondary_amount_usdc": 25.0,
        "secondary_size_shares": 25.0, 
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.95,
        "market_overrides": {
	    "total_corners": {"amount_usdc": 250.0, "size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_size_shares": 250.0, "secondary_limit_price": 0.99,},
        "soccer_halftime_result": {"amount_usdc": 250.0, "size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_size_shares": 250.0, "secondary_limit_price": 0.99,},
        "moneyline":{"amount_usdc": 250.0, "size_shares": 250.0,  "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_size_shares": 250.0, "secondary_limit_price": 0.99,},
        "spreads":{"amount_usdc": 250.0, "size_shares": 250.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 250.0, "secondary_size_shares": 250.0, "secondary_limit_price": 0.99,},
                    },
        
    },
    "ucl": {
        "amount_usdc": 5.0,
        "size_shares": 5.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
    },
    "laliga": {
        "amount_usdc": 50.0,
        "size_shares": 50.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.9,
        "secondary_amount_usdc": 25.0,
        "secondary_size_shares": 25.0, 
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.9,
        "market_overrides": {
	    "total_corners": {"amount_usdc": 150.0, "size_shares": 150.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_size_shares": 150.0, "secondary_limit_price": 0.99,},
        "soccer_halftime_result": {"amount_usdc": 150.0, "size_shares": 150.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_size_shares": 150.0, "secondary_limit_price": 0.99,},
        "moneyline":{"amount_usdc": 150.0, "size_shares": 150.0,  "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_size_shares": 150.0, "secondary_limit_price": 0.99,},
        "spreads":{"amount_usdc": 150.0, "size_shares": 150.0, "limit_price": 0.99,
                    "secondary_amount_usdc": 150.0, "secondary_size_shares": 150.0, "secondary_limit_price": 0.99,},
                    },
    },
    "rolgar": {
        "amount_usdc": 50.0,
        "size_shares": 50.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
        "secondary_amount_usdc": 50.0,
        "secondary_size_shares": 50.0, 
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.99,
    },
    "garros": {
        "amount_usdc": 25.0,
        "size_shares": 25.0,
        "time_in_force": "GTC",
        "require_presign": True,
        "limit_price": 0.99,
        "secondary_amount_usdc": 25.0,
        "secondary_size_shares": 25.0, 
        "secondary_time_in_force": "FAK",
        "secondary_limit_price": 0.99,
    },
}

# Runtime timing controls for live snapshot refresh and subscription windows.
HOTPATH_RUNTIME_POLICY = {
    "mlb": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 5,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 1800,
        "ws_core_idx": 5,
        "submitter_core_idx": 6,
    },
    "epl": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 1,
        "submitter_core_idx": 2,
    },
    "ucl": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 3,
        "submitter_core_idx": 4,
    },
    "laliga": {
        "plan_horizon_hours": 12,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 300,
        "ws_core_idx": 7,
        "submitter_core_idx": 8,
    },
    "rolgar": {
        "plan_horizon_hours": 6,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 1800,
	    "ws_core_idx": 3,
	    "submitter_code_idx": 4,
    },
    "garros": {
        "plan_horizon_hours": 6,
        "subscribe_lead_minutes": 30,
        "reload_interval_seconds": 120,
        "provider_catalog_max_age_seconds": 20000,
        "refresh_interval_seconds": 1800,
	    "ws_core_idx": 3,
	    "submitter_code_idx": 4,
    },
}
